### ISSUE TITLE
configs in the paper

### ISSUE THREAD

**Issue by KimJaehee0725** [magpie-align/magpie#37]
Hello! Thank you for this wonderful work. 
It will help my recent work for training private llm :) 

I have a question regarding the configurations among in the [recipe page](https://github.com/magpie-align/magpie/tree/main/recipes)
I can find various recipes with the language(eng/chinese), and versions. 

Which is the exact configurations for the reported model in the original paper, especially the 'MAGPIE-Pro-300K-Filtered' in the Table 1?

Thanks!

**Comment by zhangchen-xu** [comment]
It's this: [https://huggingface.co/Magpie-Align/Llama-3-8B-Magpie-Pro-SFT-300K-v0.1](https://huggingface.co/Magpie-Align/Llama-3-8B-Magpie-Pro-SFT-300K-v0.1).

You can go to the end of the page to see the detailed Axolotl configs. Note that since Axolotl has some major updates recently, you may need to slightly modify the configurations in dataset part by changing:
```
datasets:
  - path: Magpie-Align/Magpie-Pro-300K-Filtered
    type: sharegpt
    conversation: llama3
```
to something like:
```
chat_template: llama3
datasets:
  - path: Magpie-Align/Magpie-Pro-300K-Filtered
    type: chat_template
    field_messages: conversations
    # The key in the message turn that contains the role. Default is "role".
    message_field_role: from
    # The key in the message turn that contains the content. Default is "content".
    message_field_content: value
    # Optional[Dict[str, List]]. Roles mapping for the messages.
    roles:
      user: ["human", "user"]
      assistant: ["gpt", "assistant", "ai"]
      system: ["system"]
```
